CREATE TABLE IF NOT EXISTS customer_profiles (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) DEFAULT '',
    phone VARCHAR(50) DEFAULT '',
    address VARCHAR(255) DEFAULT '',
    spend NUMERIC(10,2) DEFAULT 0.00,
    tier VARCHAR(50) DEFAULT 'Standard',
    created_at TIMESTAMP WITH TIMEZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIMEZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_dashboard_layouts (
    id SERIAL PRIMARY KEY,
    customer_id INT REFERENCES customer_profiles(id) ON DELETE CASCADE,
    layout_data JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIMEZONE DEFAULT CURRENT_TIMESTAMP
);
